CrudSucesso/Models/Participante.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudSucesso.Models
{
    public class Participante
    {
        [Display(Name = "#")]
        public int Id { get; set; }
        [Required(ErrorMessage = "Campo obrigatório!")]
        [Display(Name = "Nome")]
        public string Name { get; set; }
        [Display(Name = "Data de Nascimento")]
        [DataType(DataType.Date)]
        public DateTime BirthDate { get; set; }
        [Display(Name = "Telefone")]
        public string Phone { get; set; }
        [Display(Name = "Pacote")]
        public int PacoteId { get; set; }
        public List<Pacote> Pacote { get; set; }
        public List<Atividade> Atividades { get; set; }
    }
}

CrudSucesso/Controllers/ParticipantesController.cs
using CrudSucesso.Models;
using CrudSucesso.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;

namespace CrudSucesso.Controllers
{
    public class ParticipantesController : Controller
    {
        IParticipanteService _service;
        IPacoteService _pacoteService;
        IAtividadeService _atividadeService;

        public ParticipantesController(IParticipanteService service, IPacoteService pacoteService, IAtividadeService atividadeService)
        {
            _service = service;
            _pacoteService = pacoteService;
            _atividadeService = atividadeService;
        }
        public IActionResult Index()
        {
            return View(_service.GetAll());
        }
        [HttpGet]
        public IActionResult Create()
        {
            //ViewBag.atividades = new SelectList(_atividadeService.GetAll().Select(a => new { a.Id, name = a.DescAtv + " - R$ " + a.Price}), "Id", "name");
            ViewBag.atividades = _atividadeService.GetAll().ToList();
            ViewBag.pacotes = new SelectList(_pacoteService.GetAll().Select(p => new {
                p.Id,
                name = p.DescPkg + " - R$ " + p.Price
            }), "Id", "name");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Participante participante)
        {
            if (!ModelState.IsValid) return View(participante);

            if (_service.Create(participante))
                return RedirectToAction(nameof(Index));
            else
                return View(participante);
        }
        public IActionResult Read(int id)
        {
            return _service.Get(id) != null ? View(_service.Get(id)) : NotFound();
        }
        [HttpGet]
        public IActionResult Update(int id)
        {
            return View(_service.GetAll().FirstOrDefault(p => p.Id == id));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Participante participante)
        {
            if (!ModelState.IsValid) return View(participante);

            if (_service.Update(participante))
                return RedirectToAction(nameof(Index));
            else
                return NotFound();
        }
        public IActionResult Delete(int? id)
        {
            if (_service.Delete(id))
                return RedirectToAction(nameof(Index));
            else
                return NotFound();
        }
        public IActionResult Confirm(int? id)
        {
            return _service.GetAll().FirstOrDefault(p => p.Id == id) != null ?
              View(_service.GetAll().FirstOrDefault(p => p.Id == id)) :
              RedirectToAction(nameof(Index));
        }

    }
}

CrudSucesso/Views/Participantes/Create.cshtml
@model Participante

<h2>Cadastre-se</h2>
<h6>Por favor, preencha todos os campos que não são opcionais.</h6>
<form class="col-md-4" asp-action="Create">
  <div class="mb-3">
    <label class="form-label" asp-for="Name"></label>
    <input class="form-control" asp-for="Name" required />
  </div>
  <div class="mb-3">
    <label class="control-label" asp-for="BirthDate"></label>
    <input class="form-control" asp-for="BirthDate" required />
  </div>
  <div class="mb-3">
    <label class="control-label" asp-for="Phone"></label>
    <input class="form-control" asp-for="Phone" required />
  </div>
  <div class="mb-3">
    <label class="control-label" asp-for="PacoteId"></label>
    <select class="form-control" asp-for="PacoteId" asp-items="ViewBag.pacotes"></select>
  </div>
  <div class="mb-3">
    <label class="control-label" asp-for="Atividades">Atividades opcionais</label>
    @foreach (Atividade atividade in ViewBag.atividades) { <input type="checkbox" />
    <label>@atividade.DescAtv</label>
    <br /> }
  </div>
  <input type="submit" value="Cadastrar" class="btn btn-primary" />
  <a class="btn btn-primary" asp-controller="Home" asp-action="Index">Voltar</a>
</form>

CrudSucesso/Views/Participantes/Index.cshtml
@model List<Participante>

<h2>Cadastrar participantes</h2>

<a class="btn btn-primary" asp-controller="Participantes" asp-action="Create">Cadastrar participante</a>